version: "3.9"

services:
  playground:
    command: bash -c "cd /usr/src/app && make run"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    volumes:
      - .:/usr/src/app
